export const STATES = [
  { label: "Abia", value: "Abia" },
  { label: "Adamawa", value: "Adamawa" },
  { label: "Akwa Ibom", value: "Akwa Ibom" },
  { label: "Anambra", value: "Anambra" },
  { label: "Bauchi", value: "Bauchi" },
  { label: "Bayelsa", value: "Bayelsa" },
  { label: "Benue", value: "Benue" },
  { label: "Borno", value: "Borno" },
  { label: "Cross River", value: "Cross River" },
  { label: "Delta", value: "Delta" },
  { label: "Ebonyi", value: "Ebonyi" },
  { label: "Edo", value: "Edo" },
  { label: "Ekiti", value: "Ekiti" },
  { label: "Enugu", value: "Enugu" },
  { label: "FCT - Abuja", value: "FCT - Abuja" },
  { label: "Gombe", value: "Gombe" },
  { label: "Imo", value: "Imo" },
  { label: "Jigawa", value: "Jigawa" },
  { label: "Kaduna", value: "Kaduna" },
  { label: "Kano", value: "Kano" },
  { label: "Katsina", value: "Katsina" },
  { label: "Kebbi", value: "Kebbi" },
  { label: "Kogi", value: "Kogi" },
  { label: "Kwara", value: "Kwara" },
  { label: "Lagos", value: "Lagos" },
  { label: "Nasarawa", value: "Nasarawa" },
  { label: "Niger", value: "Niger" },
  { label: "Ogun", value: "Ogun" },
  { label: "Ondo", value: "Ondo" },
  { label: "Osun", value: "Osun" },
  { label: "Oyo", value: "Oyo" },
  { label: "Plateau", value: "Plateau" },
  { label: "Rivers", value: "Rivers" },
  { label: "Sokoto", value: "Sokoto" },
  { label: "Taraba", value: "Taraba" },
  { label: "Yobe", value: "Yobe" },
  { label: "Zamfara", value: "Zamfara" },
];

export const INDUSTRIES = [
  { label: "Accounting", value: "Accounting" },
  { label: "Animation", value: "Animation" },
  { label: "Airlines/Aviation", value: "Airlines/Aviation" },
  {
    label: "Alternative Dispute Resolution",
    value: "Alternative Dispute Resolution",
  },
  { label: "Apparel & Fashion", value: "Apparel & Fashion" },
  { label: "Architecture & Planning", value: "Architecture & Planning" },
  {
    label: "Business Supplies & Equipment",
    value: "Business Supplies & Equipment",
  },
  { label: "Capital Markets", value: "Capital Markets" },
  { label: "Chemicals", value: "Chemicals" },
  { label: "Engineering", value: "Engineering" },
  { label: "Construction", value: "Construction" },
  { label: "Cosmetics", value: "Cosmetics" },
  { label: "Dairy", value: "Dairy" },
  { label: "Design", value: "Design" },
  { label: "Entertainment", value: "Entertainment" },
  { label: "Farming", value: "Farming" },
  { label: "Furniture", value: "Furniture" },
  { label: "Human Resources", value: "Human Resources" },
  { label: "Insurance", value: "Insurance" },
  { label: "Judiciary", value: "Judiciary" },
  { label: "Legal Services", value: "Legal Services" },
  { label: "Newspapers", value: "Newspapers" },
  { label: "Photography", value: "Photography" },
  { label: "Politics", value: "Politics" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Sports", value: "Sports" },
  { label: "Venture Capital", value: "Venture Capital" },
  { label: "Wholesale", value: "Wholesale" },
];

export const TECHNOLOGIES = [
  { label: "C++", value: "C++" },
  { label: "C#", value: "C#" },
  { label: "Dart/Flutter", value: "Dart/Flutter" },
  {
    label: "Java",
    value: "Java",
  },
  { label: "JavaScript", value: "JavaScript" },
  { label: "PHP", value: "PHP" },
  {
    label: "Rust",
    value: "Rust",
  },
  { label: "Mongo DB", value: "Mongo DB" },
  { label: "MySql", value: "MySql" },
  { label: "AWS", value: "AWS" },
  { label: "Digital Ocean", value: "Digital Ocean" },
  { label: "Railway", value: "Railway" },
];
